# SPDX-FileCopyrightText: 2021 Frans van Dorsselaer
#
# SPDX-License-Identifier: MIT

name: Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Install dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --configuration Release --no-restore
    - name: Test
      run: dotnet test --no-restore --verbosity normal --collect:"XPlat Code Coverage"
    - name: Package
      run: dotnet pack --configuration Release --no-build
    - name: Upload Package Artifact
      uses: actions/upload-artifact@v2
      with:
        name: nuget-package
        path: "**/*.nupkg"
    - name: Codecov
      uses: codecov/codecov-action@v1
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
    - name: setup-msbuild
      uses: microsoft/setup-msbuild@v1
    - name: Documentation Dependencies
      run: msbuild Documentation -t:restore
    - name: Documentation
      run: msbuild Documentation
    - name: Upload Documentation Artifact
      uses: actions/upload-artifact@v2
      with:
        name: documentation
        path: "Documentation/bin"
