# SPDX-FileCopyrightText: 2021 Frans van Dorsselaer
#
# SPDX-License-Identifier: MIT

---
# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json

name: Build

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

permissions:
  contents: read
  issues: read
  checks: write
  pull-requests: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup .NET
        uses: actions/setup-dotnet@v3

      - name: Cache
        uses: actions/cache@v3
        with:
          path: ~/.nuget/packages
          key: ${{ runner.os }}-nuget-${{ hashFiles('**/Directory.Packages.props') }}

      - name: Install dependencies
        run: |
          dotnet restore
          dotnet restore Documentation --no-dependencies
          dotnet tool restore

      - name: Build
        run: dotnet build --configuration Release --no-restore

      - name: Test
        run: dotnet test --configuration Release --no-build --verbosity normal --collect:"XPlat Code Coverage" --logger trx

      - name: Package
        run: dotnet pack --configuration Release --no-build

      - name: Trimmable Test
        run: |
          # NOTE: This has to rebuild Debounce as well, due to how '--use-current-runtime' works.
          # Make sure to run this test *after* building packaging, in order to not mix up the builds.
          dotnet publish TrimmableTest --use-current-runtime --configuration Release -p:PublishProfile=FolderProfile
          ./TrimmableTest/bin/Release/publish/TrimmableTest

      - name: Publish Test Results
        uses: EnricoMi/publish-unit-test-result-action@v2
        if: always()
        with:
          files: |
            **/TestResults/*.trx

      - name: Upload Package Artifact
        uses: actions/upload-artifact@v3
        with:
          name: nuget-package
          path: |
            **/*.nupkg
            **/*.snupkg

      - name: Upload Documentation Artifact
        uses: actions/upload-artifact@v3
        with:
          name: documentation
          path: Documentation/_site

      - name: Codecov
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
