# SPDX-FileCopyrightText: 2021 Frans van Dorsselaer
#
# SPDX-License-Identifier: MIT

name: REUSE

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:

    runs-on: ubuntu-latest

    steps: 
    - uses: actions/checkout@v2
    - name: REUSE Compliance Check
      uses: fsfe/reuse-action@v1
